export class Constants {
  static TIMER_NEXT_FLAG = 700;
  static TIMER_UPDATE = 1000;
  static TIME_DECREASE = 1000;
  static TIMER_GAME_IN_MS = 30000;
  static TIMER_INCREASE_GOOD_ANSWER = 1000;
  static DURATION_ANIMATION_FLAGS_AND_ANSWERS_IN_OUT = 300;
  static DURATION_ANIMATION_SCORE = 100;
  static FLAG_TRANSLATION = 300;
  static TIMER_ALERT = 10000;
  static CONVERT_MS_AND_S = 1000;
}
